kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: test
    image: maven:3-jdk-10
    commands:
      - mvn clean test