kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: http://localhost:9000
      sonar_token:
        from_secret: d34a7b98836b32a81d0a8d1754e80b639f4d6af8
