kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo This step is to ensure that the pipeline itself is functioning properly.
  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn -ntp -B clean
      - mvn -ntp -B compile
#  - name: test
#    image: maven:3-jdk-11
#    commands:
#      - mvn -ntp install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#      - mvn -ntp test -B
#  - name: code-analysis
#    image: aosapps/drone-sonar-plugin
#    settings:
#      sonar_host:
#        from_secret: sonar_host
#      sonar_token:
#        from_secret: sonar_token
#   SonarQube can't handle Pull Requests unless we get a fancier version, I think
#    when:
#      event:
#        - push
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
    files: target/synthesize-0.0.1-SNAPSHOT.jar
    when:
      event: tag
