kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host: http://localhost:9000
      sonar_token:
        from_secret: sonar_token

