kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo This step is to ensure that the pipeline itself is functioning properly.
  - name: build
    image: maven:3.6.3-jdk-11
    commands:
      - mvn -ntp -B clean compile
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn -ntp test -B
#     Since Jacoco is running our coverage reports for us, remove Test files before sending to sonar
      - rm -R src/test
  - name: code-analysis
    image: aosapps/drone-sonar-plugin:1.0
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
#   SonarQube can't handle Pull Requests unless we get a fancier version, I think
    when:
      event:
        - push
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: target/dist/*
    when:
      event: tag
