kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo This step is to ensure that the pipeline itself is functioning properly.
  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn -e -ntp -B clean |
      - mvn -e -ntp -B compile
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn -e -ntp install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn -e -ntp test -B
      - echo Deleting tests before running code analysis
      - rm -R src/test
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
