kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
  - name: notify-failure
    image: alpine
    commands:
      - echo Build failed
    when:
      status:
        - failure
  - name: notify-success
    image: alpine
    commands:
      - echo Build success